
# database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/navdb?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: gyc89,./
    driverClassName: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      schema-locations: classpath:db/test_schema.sql
#      data-locations: classpath:db/test_data.sql
#      mode: always

#mybatis:
#  mapper-locations: classpath:mapper/*.xml

# mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# Log
logging:
  config: classpath:logback.xml
  level:
    root: info

# controller
server:
  servlet:
    context-path: /api

#debug: true
